# -*- coding: utf-8 -*-
"""
/***************************************************************************
 droughtIndexer
                                 A QGIS plugin
 A plugin to Process Standardized Agricultural Drought Index.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-03
        copyright            : (C) 2024 by John Ngugi
        email                : johnngugi0407@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load droughtIndexer class from file droughtIndexer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .drought_indexer import droughtIndexer
    return droughtIndexer(iface)
